name: Update Kanban Board

on:
  push:
    paths:
      - 'watchlist.md'
  workflow_dispatch:

jobs:
  update-kanban:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug File Content
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('watchlist.md', 'utf8');
            console.log('File content:', content);
            
      - name: Create/Update Project Items
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('watchlist.md', 'utf8');
            
            // Parse sections
            const watchSection = content.split('## 📺 Watch')[1].split('## 🎬 In Progress')[0].trim();
            const inProgressSection = content.split('## 🎬 In Progress')[1].split('## ✅ Completed')[0].trim();
            const completedSection = content.split('## ✅ Completed')[1]?.trim() || '';
            
            // Extract items
            const watchItems = (watchSection.match(/- \[ \] (.*?)(?=\n|$)/g) || [])
              .map(item => item.replace('- [ ] ', '').trim());
            const inProgressItems = (inProgressSection.match(/- \[.\] (.*?)(?=\n|$)/g) || [])
              .map(item => item.replace(/- \[.\] /, '').trim());
            const completedItems = (completedSection.match(/- \[x\] (.*?)(?=\n|$)/g) || [])
              .map(item => item.replace('- [x] ', '').trim());
            
            const addToProject = async (title, status) => {
              console.log(`Attempting to add item: "${title}" with status: "${status}"`);
              const escapedTitle = title.replace(/"/g, '\\"');
              
              // First, create the item
              const createMutation = `
                mutation {
                  addProjectV2DraftIssue(input: {
                    projectId: "PVT_kwHOCw13Q84Ay6MG"
                    title: "${escapedTitle}"
                  }) {
                    projectItem {
                      id
                    }
                  }
                }
              `;
              
              try {
                const result = await github.graphql(createMutation);
                const itemId = result.addProjectV2DraftIssue.projectItem.id;
                console.log('Created item:', itemId);
                
                // Then update its status
                const updateMutation = `
                  mutation {
                    updateProjectV2ItemFieldValue(input: {
                      projectId: "PVT_kwHOCw13Q84Ay6MG"
                      itemId: "${itemId}"
                      fieldId: "PVTSSF_lAHOCw13Q84Ay6MGzgoySwo"
                      value: "${status}"
                    }) {
                      projectV2Item {
                        id
                      }
                    }
                  }
                `;
                
                await github.graphql(updateMutation);
                console.log('Successfully updated status for:', title);
                
              } catch (error) {
                console.error('Error processing item:', title);
                console.error('Error details:', JSON.stringify(error, null, 2));
                throw error;
              }
            };

            // Add items with error handling
            try {
              console.log('Starting to add watch items...');
              for (const item of watchItems) {
                await addToProject(item, "Todo");
              }
              
              console.log('Starting to add in-progress items...');
              for (const item of inProgressItems) {
                await addToProject(item, "In Progress");
              }
              
              console.log('Starting to add completed items...');
              for (const item of completedItems) {
                await addToProject(item, "Done");
              }
            } catch (error) {
              console.error('Failed during item creation:', error);
              throw error;
            }
