name: Update Kanban Board

on:
  push:
    paths:
      - 'watchlist.md'
  workflow_dispatch:

jobs:
  update-kanban:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug File Content
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('watchlist.md', 'utf8');
            console.log('File content:', content);
            
      - name: Create/Update Project Items
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('watchlist.md', 'utf8');
            
            // Parse sections
            const watchSection = content.split('## 📺 Watch')[1].split('## 🎬 In Progress')[0].trim();
            const inProgressSection = content.split('## 🎬 In Progress')[1].split('## ✅ Completed')[0].trim();
            const completedSection = content.split('## ✅ Completed')[1]?.trim() || '';
            
            // Extract items with tags
            const extractTitleAndTag = (item) => {
              const match = item.match(/(.*?)\s*`(\w+)`$/);
              if (match) {
                return {
                  title: match[1].trim(),
                  tag: match[2]
                };
              }
              return {
                title: item,
                tag: null
              };
            };

            const watchItems = (watchSection.match(/- \[ \] (.*?)(?=\n|$)/g) || [])
              .map(item => {
                const cleanItem = item.replace('- [ ] ', '').trim();
                return extractTitleAndTag(cleanItem);
              });

            const inProgressItems = (inProgressSection.match(/- \[.\] (.*?)(?=\n|$)/g) || [])
              .map(item => {
                const cleanItem = item.replace(/- \[.\] /, '').trim();
                return extractTitleAndTag(cleanItem);
              });

            const completedItems = (completedSection.match(/- \[x\] (.*?)(?=\n|$)/g) || [])
              .map(item => {
                const cleanItem = item.replace('- [x] ', '').trim();
                return extractTitleAndTag(cleanItem);
              });

            // First, get the status field options
            const getStatusFieldOptions = async () => {
              const query = `
                query {
                  node(id: "PVT_kwHOCw13Q84Ay6MG") {
                    ... on ProjectV2 {
                      field(name: "Status") {
                        ... on ProjectV2SingleSelectField {
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              const result = await github.graphql(query);
              return result.node.field.options;
            };

            const statusOptions = await getStatusFieldOptions();
            const getOptionId = (name) => {
              const option = statusOptions.find(opt => opt.name === name);
              return option ? option.id : null;
            };
            
            const addToProject = async (itemData, status) => {
              console.log(`Attempting to add item: "${itemData.title}" with status: "${status}"`);
              const escapedTitle = itemData.title.replace(/"/g, '\\"');
              const description = itemData.tag ? `Type: ${itemData.tag.toUpperCase()}` : '';
              const escapedDescription = description.replace(/"/g, '\\"');
              const statusOptionId = getOptionId(status);
              
              if (!statusOptionId) {
                throw new Error(`Status option not found: ${status}`);
              }
              
              // Create the item with description
              const createMutation = `
                mutation {
                  addProjectV2DraftIssue(input: {
                    projectId: "PVT_kwHOCw13Q84Ay6MG"
                    title: "${escapedTitle}"
                    body: "${escapedDescription}"
                  }) {
                    projectItem {
                      id
                    }
                  }
                }
              `;
              
              try {
                const result = await github.graphql(createMutation);
                const itemId = result.addProjectV2DraftIssue.projectItem.id;
                console.log('Created item:', itemId);
                
                // Update its status
                const updateMutation = `
                  mutation {
                    updateProjectV2ItemFieldValue(input: {
                      projectId: "PVT_kwHOCw13Q84Ay6MG"
                      itemId: "${itemId}"
                      fieldId: "PVTSSF_lAHOCw13Q84Ay6MGzgoySwo"
                      value: { singleSelectOptionId: "${statusOptionId}" }
                    }) {
                      projectV2Item {
                        id
                      }
                    }
                  }
                `;
                
                await github.graphql(updateMutation);
                console.log('Successfully updated status for:', itemData.title);
                
              } catch (error) {
                console.error('Error processing item:', itemData.title);
                console.error('Error details:', JSON.stringify(error, null, 2));
                throw error;
              }
            };

            // Add this function to get existing items from the project
            const getExistingItems = async () => {
              const query = `
                query {
                  node(id: "PVT_kwHOCw13Q84Ay6MG") {
                    ... on ProjectV2 {
                      items(first: 100) {
                        nodes {
                          id
                          content {
                            ... on DraftIssue {
                              title
                            }
                          }
                          fieldValues(first: 8) {
                            nodes {
                              ... on ProjectV2ItemFieldSingleSelectValue {
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              const result = await github.graphql(query);
              return result.node.items.nodes.map(item => ({
                id: item.id,
                title: item.content?.title || '',
                status: item.fieldValues.nodes.find(n => n.name)?.name || null
              }));
            };

            const syncProject = async () => {
              // Get existing items
              const existingItems = await getExistingItems();
              
              // Helper function to find existing item
              const findExistingItem = (title) => {
                return existingItems.find(item => item.title === title);
              };

              // Process watch items
              for (const item of watchItems) {
                const existing = findExistingItem(item.title);
                if (!existing) {
                  // Create new item
                  await addToProject(item, "Todo");
                } else if (existing.status !== "Todo") {
                  // Update status if different
                  await updateItemStatus(existing.id, "Todo");
                }
              }

              // Process in-progress items
              for (const item of inProgressItems) {
                const existing = findExistingItem(item.title);
                if (!existing) {
                  await addToProject(item, "In Progress");
                } else if (existing.status !== "In Progress") {
                  await updateItemStatus(existing.id, "In Progress");
                }
              }

              // Process completed items
              for (const item of completedItems) {
                const existing = findExistingItem(item.title);
                if (!existing) {
                  await addToProject(item, "Done");
                } else if (existing.status !== "Done") {
                  await updateItemStatus(existing.id, "Done");
                }
              }

              // Optionally: Remove items that are no longer in the watchlist
              const allWatchlistTitles = [
                ...watchItems.map(i => i.title),
                ...inProgressItems.map(i => i.title),
                ...completedItems.map(i => i.title)
              ];

              for (const existing of existingItems) {
                if (!allWatchlistTitles.includes(existing.title)) {
                  await deleteProjectItem(existing.id);
                }
              }
            };

            // Add helper function to update status
            const updateItemStatus = async (itemId, status) => {
              const statusOptionId = getOptionId(status);
              const updateMutation = `
                mutation {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: "PVT_kwHOCw13Q84Ay6MG"
                    itemId: "${itemId}"
                    fieldId: "PVTSSF_lAHOCw13Q84Ay6MGzgoySwo"
                    value: { singleSelectOptionId: "${statusOptionId}" }
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;
              
              await github.graphql(updateMutation);
            };

            // Add helper function to delete items
            const deleteProjectItem = async (itemId) => {
              const deleteMutation = `
                mutation {
                  deleteProjectV2Item(input: {
                    projectId: "PVT_kwHOCw13Q84Ay6MG"
                    itemId: "${itemId}"
                  }) {
                    deletedItemId
                  }
                }
              `;
              
              await github.graphql(deleteMutation);
            };

            // Replace the try-catch block with this:
            try {
              console.log('Starting to sync project...');
              await syncProject();
              console.log('Project sync completed');
            } catch (error) {
              console.error('Failed during project sync:', error);
              throw error;
            }
